### ISSUE TITLE
Delta debugger runs for at least twice the time I pass in as the timeout.

### ISSUE THREAD

**Issue by amordahl** [Pancax/SADeltaDebugger#2]
I think I brought this issue up with you in person before but it still appears to be happening. When I pass `--timeout 120` (indicating a 120 minute timeout), I get output including this:

```
Timers: 
recreate_timer: 0
compile_timer: 0
method_timer: 0
binary_timer: 7203
jdeps_timer: 1
hdd_timer: 7210
program_timer: 14441
setup_timer: 11
```

14441 seconds is almost exactly 4 hours.

**Comment by amordahl** [comment]
Furthmore I get a few cases that go far over even 4 hours. Like this:

```
Timers: 
recreate_timer: 0
compile_timer: 0
method_timer: 0
binary_timer: 7791
jdeps_timer: 2
hdd_timer: 7696
program_timer: 16280
setup_timer: 16
```

Which is almost 4.5 hours.

**Comment by Pancax** [comment]
Are you wanting a 120 minute timeout to mean 120 minutes for the entire reduction (cdg + hdd) combined?

**Comment by amordahl** [comment]
Yes. If you want to have separate timeouts you can do that but if you have an overall timeout I think that should be for the whole delta debugging process.

**Comment by Pancax** [comment]
https://github.com/Pancax/SADeltaDebugger/commit/98173c5eadf3d884ac6e61a1a4cefad30e0c3441
